# Generated by Django 3.1.3 on 2020-12-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_test', '0003_blastresult_blast_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastresult',
            name='result_no',
            field=models.CharField(max_length=255),
        ),
    ]
