# Generated by Django 3.1.3 on 2020-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_test', '0004_auto_20201201_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastresult',
            name='result_no',
            field=models.IntegerField(default=1),
        ),
    ]
