# Generated by Django 3.1.3 on 2020-12-01 05:13

import blast_test.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blast_test', '0005_auto_20201201_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastresult',
            name='blast_job',
            field=models.ForeignKey(default=blast_test.models.BlastJob, on_delete=django.db.models.deletion.CASCADE, to='blast_test.blastjob'),
        ),
    ]
