# Generated by Django 3.1.3 on 2020-12-01 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blast_test', '0008_remove_blastresult_blast_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastresult',
            name='blast_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blast_test.blastjob'),
        ),
        migrations.AlterField(
            model_name='blastresult',
            name='result_no',
            field=models.IntegerField(),
        ),
    ]
