# Generated by Django 3.1.3 on 2020-12-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blast_test', '0009_auto_20201201_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastresult',
            name='blast_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast_test.blastjob'),
        ),
    ]
